services:
  api:
    build: ./analytics-api
    container_name: api-dev
    ports:
      - 8000:8000
    depends_on:
      mongo:
        condition: service_started
      redis:
        condition: service_healthy



  producer:
    build: ./producer
    container_name: producer-dev
    depends_on:
      api:
        condition: service_started


  consumer:
    build: ./consumer
    container_name: consumer-dev
    depends_on:
      mongo:
        condition: service_started
      redis:
        condition: service_healthy



  redis:
    image: redis:latest
    container_name: redis-dev
    healthcheck:
      test: [ "CMD-SHELL", "redis-cli ping | grep PONG" ]
      interval: 1s
      timeout: 3s
      retries: 5
    command: [ "redis-server" ]

  mongo:
    image: mongo
    container_name: mongo-dev
    environment:
      MONGO_INITDB_DATABASE: project


